import { Transaction, CategorizationResult } from '@/models/types';

const MERCHANT_LOOKUP: Record<string, { categoryId: string; subcategoryId: string; merchant: string; tags: string[] }> = {
  // ── Groceries ────────────────────────────────────────────────────────────────
  'whole foods': { categoryId: 'groceries', subcategoryId: 'groceries-supermarket', merchant: 'Whole Foods', tags: ['grocery'] },
  'trader joe': { categoryId: 'groceries', subcategoryId: 'groceries-supermarket', merchant: "Trader Joe's", tags: ['grocery'] },
  'safeway': { categoryId: 'groceries', subcategoryId: 'groceries-supermarket', merchant: 'Safeway', tags: ['grocery'] },
  'kroger': { categoryId: 'groceries', subcategoryId: 'groceries-supermarket', merchant: 'Kroger', tags: ['grocery'] },
  'costco': { categoryId: 'groceries', subcategoryId: 'groceries-supermarket', merchant: 'Costco', tags: ['grocery', 'bulk'] },
  'albertsons': { categoryId: 'groceries', subcategoryId: 'groceries-supermarket', merchant: 'Albertsons', tags: ['grocery'] },
  'fred meyer': { categoryId: 'groceries', subcategoryId: 'groceries-supermarket', merchant: 'Fred Meyer', tags: ['grocery'] },
  'qfc': { categoryId: 'groceries', subcategoryId: 'groceries-supermarket', merchant: 'QFC', tags: ['grocery'] },
  'publix': { categoryId: 'groceries', subcategoryId: 'groceries-supermarket', merchant: 'Publix', tags: ['grocery'] },
  'h-e-b': { categoryId: 'groceries', subcategoryId: 'groceries-supermarket', merchant: 'H-E-B', tags: ['grocery'] },
  'heb ': { categoryId: 'groceries', subcategoryId: 'groceries-supermarket', merchant: 'H-E-B', tags: ['grocery'] },
  'aldi': { categoryId: 'groceries', subcategoryId: 'groceries-supermarket', merchant: 'Aldi', tags: ['grocery'] },
  'wegmans': { categoryId: 'groceries', subcategoryId: 'groceries-supermarket', merchant: 'Wegmans', tags: ['grocery'] },
  'sprouts': { categoryId: 'groceries', subcategoryId: 'groceries-specialty', merchant: 'Sprouts', tags: ['grocery', 'organic'] },
  'winco': { categoryId: 'groceries', subcategoryId: 'groceries-supermarket', merchant: 'WinCo', tags: ['grocery'] },
  'meijer': { categoryId: 'groceries', subcategoryId: 'groceries-supermarket', merchant: 'Meijer', tags: ['grocery'] },
  'stop & shop': { categoryId: 'groceries', subcategoryId: 'groceries-supermarket', merchant: 'Stop & Shop', tags: ['grocery'] },
  'giant food': { categoryId: 'groceries', subcategoryId: 'groceries-supermarket', merchant: 'Giant Food', tags: ['grocery'] },
  'harris teeter': { categoryId: 'groceries', subcategoryId: 'groceries-supermarket', merchant: 'Harris Teeter', tags: ['grocery'] },
  'food lion': { categoryId: 'groceries', subcategoryId: 'groceries-supermarket', merchant: 'Food Lion', tags: ['grocery'] },
  'vons': { categoryId: 'groceries', subcategoryId: 'groceries-supermarket', merchant: 'Vons', tags: ['grocery'] },
  'ralphs': { categoryId: 'groceries', subcategoryId: 'groceries-supermarket', merchant: "Ralph's", tags: ['grocery'] },
  'tom thumb': { categoryId: 'groceries', subcategoryId: 'groceries-supermarket', merchant: 'Tom Thumb', tags: ['grocery'] },
  'market basket': { categoryId: 'groceries', subcategoryId: 'groceries-supermarket', merchant: 'Market Basket', tags: ['grocery'] },
  'natural grocers': { categoryId: 'groceries', subcategoryId: 'groceries-specialty', merchant: 'Natural Grocers', tags: ['grocery', 'organic'] },
  'fresh market': { categoryId: 'groceries', subcategoryId: 'groceries-specialty', merchant: 'The Fresh Market', tags: ['grocery'] },
  'smart & final': { categoryId: 'groceries', subcategoryId: 'groceries-supermarket', merchant: 'Smart & Final', tags: ['grocery'] },
  'grocery outlet': { categoryId: 'groceries', subcategoryId: 'groceries-supermarket', merchant: 'Grocery Outlet', tags: ['grocery'] },

  // ── Dining & Restaurants ─────────────────────────────────────────────────────
  'starbucks': { categoryId: 'dining', subcategoryId: 'dining-coffee', merchant: 'Starbucks', tags: ['coffee', 'recurring'] },
  'dunkin': { categoryId: 'dining', subcategoryId: 'dining-coffee', merchant: "Dunkin'", tags: ['coffee'] },
  'dutch bros': { categoryId: 'dining', subcategoryId: 'dining-coffee', merchant: 'Dutch Bros', tags: ['coffee'] },
  'peets coffee': { categoryId: 'dining', subcategoryId: 'dining-coffee', merchant: "Peet's Coffee", tags: ['coffee'] },
  "peet's": { categoryId: 'dining', subcategoryId: 'dining-coffee', merchant: "Peet's Coffee", tags: ['coffee'] },
  'mcdonald': { categoryId: 'dining', subcategoryId: 'dining-fast-food', merchant: "McDonald's", tags: ['fast-food'] },
  'chipotle': { categoryId: 'dining', subcategoryId: 'dining-fast-food', merchant: 'Chipotle', tags: ['fast-food'] },
  'taco bell': { categoryId: 'dining', subcategoryId: 'dining-fast-food', merchant: 'Taco Bell', tags: ['fast-food'] },
  'burger king': { categoryId: 'dining', subcategoryId: 'dining-fast-food', merchant: 'Burger King', tags: ['fast-food'] },
  "wendy's": { categoryId: 'dining', subcategoryId: 'dining-fast-food', merchant: "Wendy's", tags: ['fast-food'] },
  'wendys': { categoryId: 'dining', subcategoryId: 'dining-fast-food', merchant: "Wendy's", tags: ['fast-food'] },
  'chick-fil-a': { categoryId: 'dining', subcategoryId: 'dining-fast-food', merchant: 'Chick-fil-A', tags: ['fast-food'] },
  'chickfila': { categoryId: 'dining', subcategoryId: 'dining-fast-food', merchant: 'Chick-fil-A', tags: ['fast-food'] },
  'popeyes': { categoryId: 'dining', subcategoryId: 'dining-fast-food', merchant: 'Popeyes', tags: ['fast-food'] },
  'kfc': { categoryId: 'dining', subcategoryId: 'dining-fast-food', merchant: 'KFC', tags: ['fast-food'] },
  'subway': { categoryId: 'dining', subcategoryId: 'dining-fast-food', merchant: 'Subway', tags: ['fast-food'] },
  'panera': { categoryId: 'dining', subcategoryId: 'dining-fast-food', merchant: 'Panera Bread', tags: ['fast-food'] },
  'five guys': { categoryId: 'dining', subcategoryId: 'dining-fast-food', merchant: 'Five Guys', tags: ['fast-food'] },
  'shake shack': { categoryId: 'dining', subcategoryId: 'dining-fast-food', merchant: 'Shake Shack', tags: ['fast-food'] },
  "in-n-out": { categoryId: 'dining', subcategoryId: 'dining-fast-food', merchant: 'In-N-Out', tags: ['fast-food'] },
  'raising cane': { categoryId: 'dining', subcategoryId: 'dining-fast-food', merchant: "Raising Cane's", tags: ['fast-food'] },
  'panda express': { categoryId: 'dining', subcategoryId: 'dining-fast-food', merchant: 'Panda Express', tags: ['fast-food'] },
  'jimmy john': { categoryId: 'dining', subcategoryId: 'dining-fast-food', merchant: "Jimmy John's", tags: ['fast-food'] },
  'jersey mike': { categoryId: 'dining', subcategoryId: 'dining-fast-food', merchant: "Jersey Mike's", tags: ['fast-food'] },
  'firehouse subs': { categoryId: 'dining', subcategoryId: 'dining-fast-food', merchant: 'Firehouse Subs', tags: ['fast-food'] },
  'olive garden': { categoryId: 'dining', subcategoryId: 'dining-restaurants', merchant: 'Olive Garden', tags: ['restaurant'] },
  'applebee': { categoryId: 'dining', subcategoryId: 'dining-restaurants', merchant: "Applebee's", tags: ['restaurant'] },
  "chili's": { categoryId: 'dining', subcategoryId: 'dining-restaurants', merchant: "Chili's", tags: ['restaurant'] },
  'chilís': { categoryId: 'dining', subcategoryId: 'dining-restaurants', merchant: "Chili's", tags: ['restaurant'] },
  "denny's": { categoryId: 'dining', subcategoryId: 'dining-restaurants', merchant: "Denny's", tags: ['restaurant'] },
  'dennys': { categoryId: 'dining', subcategoryId: 'dining-restaurants', merchant: "Denny's", tags: ['restaurant'] },
  'ihop': { categoryId: 'dining', subcategoryId: 'dining-restaurants', merchant: 'IHOP', tags: ['restaurant'] },
  'outback': { categoryId: 'dining', subcategoryId: 'dining-restaurants', merchant: 'Outback Steakhouse', tags: ['restaurant'] },
  'red robin': { categoryId: 'dining', subcategoryId: 'dining-restaurants', merchant: 'Red Robin', tags: ['restaurant'] },
  'texas roadhouse': { categoryId: 'dining', subcategoryId: 'dining-restaurants', merchant: 'Texas Roadhouse', tags: ['restaurant'] },
  "buffalo wild wings": { categoryId: 'dining', subcategoryId: 'dining-restaurants', merchant: 'Buffalo Wild Wings', tags: ['restaurant', 'bars'] },
  'doordash': { categoryId: 'dining', subcategoryId: 'dining-delivery', merchant: 'DoorDash', tags: ['delivery', 'food-delivery'] },
  'ubereats': { categoryId: 'dining', subcategoryId: 'dining-delivery', merchant: 'Uber Eats', tags: ['delivery', 'food-delivery'] },
  'grubhub': { categoryId: 'dining', subcategoryId: 'dining-delivery', merchant: 'Grubhub', tags: ['delivery', 'food-delivery'] },
  'instacart': { categoryId: 'groceries', subcategoryId: 'groceries-supermarket', merchant: 'Instacart', tags: ['grocery', 'delivery'] },
  'gopuff': { categoryId: 'dining', subcategoryId: 'dining-delivery', merchant: 'GoPuff', tags: ['delivery'] },
  'postmates': { categoryId: 'dining', subcategoryId: 'dining-delivery', merchant: 'Postmates', tags: ['delivery', 'food-delivery'] },

  // ── Transportation ───────────────────────────────────────────────────────────
  'uber': { categoryId: 'transportation', subcategoryId: 'transport-rideshare', merchant: 'Uber', tags: ['rideshare'] },
  'lyft': { categoryId: 'transportation', subcategoryId: 'transport-rideshare', merchant: 'Lyft', tags: ['rideshare'] },
  'exxon': { categoryId: 'transportation', subcategoryId: 'transport-gas', merchant: 'Exxon', tags: ['gas'] },
  'shell': { categoryId: 'transportation', subcategoryId: 'transport-gas', merchant: 'Shell', tags: ['gas'] },
  'chevron': { categoryId: 'transportation', subcategoryId: 'transport-gas', merchant: 'Chevron', tags: ['gas'] },
  'bp ': { categoryId: 'transportation', subcategoryId: 'transport-gas', merchant: 'BP', tags: ['gas'] },
  'marathon': { categoryId: 'transportation', subcategoryId: 'transport-gas', merchant: 'Marathon', tags: ['gas'] },
  'sunoco': { categoryId: 'transportation', subcategoryId: 'transport-gas', merchant: 'Sunoco', tags: ['gas'] },
  'texaco': { categoryId: 'transportation', subcategoryId: 'transport-gas', merchant: 'Texaco', tags: ['gas'] },
  'circle k': { categoryId: 'transportation', subcategoryId: 'transport-gas', merchant: 'Circle K', tags: ['gas'] },
  'speedway': { categoryId: 'transportation', subcategoryId: 'transport-gas', merchant: 'Speedway', tags: ['gas'] },
  'racetrac': { categoryId: 'transportation', subcategoryId: 'transport-gas', merchant: 'RaceTrac', tags: ['gas'] },
  'wawa': { categoryId: 'transportation', subcategoryId: 'transport-gas', merchant: 'Wawa', tags: ['gas', 'convenience'] },
  'sheetz': { categoryId: 'transportation', subcategoryId: 'transport-gas', merchant: 'Sheetz', tags: ['gas', 'convenience'] },
  'kwik trip': { categoryId: 'transportation', subcategoryId: 'transport-gas', merchant: 'Kwik Trip', tags: ['gas'] },
  'casey': { categoryId: 'transportation', subcategoryId: 'transport-gas', merchant: "Casey's", tags: ['gas'] },
  'valero': { categoryId: 'transportation', subcategoryId: 'transport-gas', merchant: 'Valero', tags: ['gas'] },
  'sinclair': { categoryId: 'transportation', subcategoryId: 'transport-gas', merchant: 'Sinclair', tags: ['gas'] },
  '76 ': { categoryId: 'transportation', subcategoryId: 'transport-gas', merchant: 'Phillips 76', tags: ['gas'] },
  'phillips 66': { categoryId: 'transportation', subcategoryId: 'transport-gas', merchant: 'Phillips 66', tags: ['gas'] },
  'parking': { categoryId: 'transportation', subcategoryId: 'transport-parking', merchant: 'Parking', tags: ['parking'] },
  'spothero': { categoryId: 'transportation', subcategoryId: 'transport-parking', merchant: 'SpotHero', tags: ['parking'] },
  'parkwhiz': { categoryId: 'transportation', subcategoryId: 'transport-parking', merchant: 'ParkWhiz', tags: ['parking'] },
  'metro ': { categoryId: 'transportation', subcategoryId: 'transport-public', merchant: 'Metro Transit', tags: ['transit'] },
  'bart ': { categoryId: 'transportation', subcategoryId: 'transport-public', merchant: 'BART', tags: ['transit'] },
  'mta ': { categoryId: 'transportation', subcategoryId: 'transport-public', merchant: 'MTA', tags: ['transit'] },
  'clipper card': { categoryId: 'transportation', subcategoryId: 'transport-public', merchant: 'Clipper Card', tags: ['transit'] },
  'presto card': { categoryId: 'transportation', subcategoryId: 'transport-public', merchant: 'Presto Card', tags: ['transit'] },
  'autozone': { categoryId: 'transportation', subcategoryId: 'transport-auto', merchant: 'AutoZone', tags: ['auto'] },
  "o'reilly auto": { categoryId: 'transportation', subcategoryId: 'transport-auto', merchant: "O'Reilly Auto", tags: ['auto'] },
  'advance auto': { categoryId: 'transportation', subcategoryId: 'transport-auto', merchant: 'Advance Auto Parts', tags: ['auto'] },
  'jiffy lube': { categoryId: 'transportation', subcategoryId: 'transport-auto', merchant: 'Jiffy Lube', tags: ['auto', 'maintenance'] },
  'firestone': { categoryId: 'transportation', subcategoryId: 'transport-auto', merchant: 'Firestone', tags: ['auto', 'tires'] },
  'pep boys': { categoryId: 'transportation', subcategoryId: 'transport-auto', merchant: 'Pep Boys', tags: ['auto'] },
  'midas': { categoryId: 'transportation', subcategoryId: 'transport-auto', merchant: 'Midas', tags: ['auto', 'maintenance'] },
  'enterprise rent': { categoryId: 'travel', subcategoryId: 'travel-car-rental', merchant: 'Enterprise', tags: ['car-rental', 'travel'] },
  'hertz': { categoryId: 'travel', subcategoryId: 'travel-car-rental', merchant: 'Hertz', tags: ['car-rental', 'travel'] },
  'avis': { categoryId: 'travel', subcategoryId: 'travel-car-rental', merchant: 'Avis', tags: ['car-rental', 'travel'] },
  'budget car': { categoryId: 'travel', subcategoryId: 'travel-car-rental', merchant: 'Budget Car Rental', tags: ['car-rental', 'travel'] },
  'e-zpass': { categoryId: 'transportation', subcategoryId: 'transport-auto', merchant: 'E-ZPass', tags: ['toll', 'auto'] },
  'fastrak': { categoryId: 'transportation', subcategoryId: 'transport-auto', merchant: 'FasTrak', tags: ['toll', 'auto'] },
  'sunpass': { categoryId: 'transportation', subcategoryId: 'transport-auto', merchant: 'SunPass', tags: ['toll', 'auto'] },
  'carmax': { categoryId: 'transportation', subcategoryId: 'transport-auto', merchant: 'CarMax', tags: ['auto'] },

  // ── Shopping ─────────────────────────────────────────────────────────────────
  'amazon': { categoryId: 'shopping', subcategoryId: 'shopping-amazon', merchant: 'Amazon', tags: ['online', 'amazon'] },
  'amzn': { categoryId: 'shopping', subcategoryId: 'shopping-amazon', merchant: 'Amazon', tags: ['online', 'amazon'] },
  'apple.com': { categoryId: 'shopping', subcategoryId: 'shopping-electronics', merchant: 'Apple', tags: ['electronics'] },
  'apple store': { categoryId: 'shopping', subcategoryId: 'shopping-electronics', merchant: 'Apple Store', tags: ['electronics'] },
  'best buy': { categoryId: 'shopping', subcategoryId: 'shopping-electronics', merchant: 'Best Buy', tags: ['electronics'] },
  'target': { categoryId: 'shopping', subcategoryId: 'shopping-general', merchant: 'Target', tags: ['retail'] },
  'walmart': { categoryId: 'shopping', subcategoryId: 'shopping-general', merchant: 'Walmart', tags: ['retail'] },
  'home depot': { categoryId: 'shopping', subcategoryId: 'shopping-home', merchant: 'Home Depot', tags: ['home-improvement'] },
  "lowe's": { categoryId: 'shopping', subcategoryId: 'shopping-home', merchant: "Lowe's", tags: ['home-improvement'] },
  'lowes': { categoryId: 'shopping', subcategoryId: 'shopping-home', merchant: "Lowe's", tags: ['home-improvement'] },
  'ikea': { categoryId: 'shopping', subcategoryId: 'shopping-home', merchant: 'IKEA', tags: ['furniture', 'home'] },
  'wayfair': { categoryId: 'shopping', subcategoryId: 'shopping-home', merchant: 'Wayfair', tags: ['furniture', 'home', 'online'] },
  'bed bath': { categoryId: 'shopping', subcategoryId: 'shopping-home', merchant: 'Bed Bath & Beyond', tags: ['home'] },
  'crate & barrel': { categoryId: 'shopping', subcategoryId: 'shopping-home', merchant: 'Crate & Barrel', tags: ['home', 'furniture'] },
  'williams sonoma': { categoryId: 'shopping', subcategoryId: 'shopping-home', merchant: 'Williams-Sonoma', tags: ['home', 'kitchen'] },
  'pottery barn': { categoryId: 'shopping', subcategoryId: 'shopping-home', merchant: 'Pottery Barn', tags: ['home', 'furniture'] },
  'west elm': { categoryId: 'shopping', subcategoryId: 'shopping-home', merchant: 'West Elm', tags: ['home', 'furniture'] },
  'gap': { categoryId: 'shopping', subcategoryId: 'shopping-clothing', merchant: 'Gap', tags: ['clothing'] },
  'h&m': { categoryId: 'shopping', subcategoryId: 'shopping-clothing', merchant: 'H&M', tags: ['clothing'] },
  'zara': { categoryId: 'shopping', subcategoryId: 'shopping-clothing', merchant: 'Zara', tags: ['clothing'] },
  'tj maxx': { categoryId: 'shopping', subcategoryId: 'shopping-clothing', merchant: 'TJ Maxx', tags: ['clothing', 'discount'] },
  'tjmaxx': { categoryId: 'shopping', subcategoryId: 'shopping-clothing', merchant: 'TJ Maxx', tags: ['clothing', 'discount'] },
  'marshalls': { categoryId: 'shopping', subcategoryId: 'shopping-clothing', merchant: 'Marshalls', tags: ['clothing', 'discount'] },
  'nordstrom': { categoryId: 'shopping', subcategoryId: 'shopping-clothing', merchant: 'Nordstrom', tags: ['clothing'] },
  "macy's": { categoryId: 'shopping', subcategoryId: 'shopping-clothing', merchant: "Macy's", tags: ['clothing'] },
  'macys': { categoryId: 'shopping', subcategoryId: 'shopping-clothing', merchant: "Macy's", tags: ['clothing'] },
  'old navy': { categoryId: 'shopping', subcategoryId: 'shopping-clothing', merchant: 'Old Navy', tags: ['clothing'] },
  'banana republic': { categoryId: 'shopping', subcategoryId: 'shopping-clothing', merchant: 'Banana Republic', tags: ['clothing'] },
  'ann taylor': { categoryId: 'shopping', subcategoryId: 'shopping-clothing', merchant: 'Ann Taylor', tags: ['clothing'] },
  'j.crew': { categoryId: 'shopping', subcategoryId: 'shopping-clothing', merchant: 'J.Crew', tags: ['clothing'] },
  'athleta': { categoryId: 'shopping', subcategoryId: 'shopping-clothing', merchant: 'Athleta', tags: ['clothing', 'athletic'] },
  'lululemon': { categoryId: 'shopping', subcategoryId: 'shopping-clothing', merchant: 'Lululemon', tags: ['clothing', 'athletic'] },
  'nike': { categoryId: 'shopping', subcategoryId: 'shopping-clothing', merchant: 'Nike', tags: ['clothing', 'athletic'] },
  'adidas': { categoryId: 'shopping', subcategoryId: 'shopping-clothing', merchant: 'Adidas', tags: ['clothing', 'athletic'] },
  'under armour': { categoryId: 'shopping', subcategoryId: 'shopping-clothing', merchant: 'Under Armour', tags: ['clothing', 'athletic'] },
  'ross stores': { categoryId: 'shopping', subcategoryId: 'shopping-clothing', merchant: 'Ross', tags: ['clothing', 'discount'] },
  'ross dress': { categoryId: 'shopping', subcategoryId: 'shopping-clothing', merchant: 'Ross', tags: ['clothing', 'discount'] },
  'burlington': { categoryId: 'shopping', subcategoryId: 'shopping-clothing', merchant: 'Burlington', tags: ['clothing', 'discount'] },
  'dollar tree': { categoryId: 'shopping', subcategoryId: 'shopping-general', merchant: 'Dollar Tree', tags: ['discount'] },
  'dollar general': { categoryId: 'shopping', subcategoryId: 'shopping-general', merchant: 'Dollar General', tags: ['discount'] },
  'five below': { categoryId: 'shopping', subcategoryId: 'shopping-general', merchant: 'Five Below', tags: ['discount'] },
  'sephora': { categoryId: 'health', subcategoryId: 'health-medical', merchant: 'Sephora', tags: ['beauty', 'personal-care'] },
  'ulta': { categoryId: 'health', subcategoryId: 'health-medical', merchant: 'Ulta Beauty', tags: ['beauty', 'personal-care'] },
  'bath & body': { categoryId: 'health', subcategoryId: 'health-medical', merchant: 'Bath & Body Works', tags: ['beauty', 'personal-care'] },
  'ebay': { categoryId: 'shopping', subcategoryId: 'shopping-general', merchant: 'eBay', tags: ['online'] },
  'etsy': { categoryId: 'shopping', subcategoryId: 'shopping-general', merchant: 'Etsy', tags: ['online'] },
  'chewy': { categoryId: 'pets', subcategoryId: 'pets-food', merchant: 'Chewy', tags: ['pets', 'online'] },
  'petsmart': { categoryId: 'pets', subcategoryId: 'pets-food', merchant: 'PetSmart', tags: ['pets'] },
  'petco': { categoryId: 'pets', subcategoryId: 'pets-food', merchant: 'Petco', tags: ['pets'] },

  // ── Subscriptions & Software ─────────────────────────────────────────────────
  'netflix': { categoryId: 'subscriptions', subcategoryId: 'subs-streaming', merchant: 'Netflix', tags: ['streaming', 'subscription', 'recurring'] },
  'spotify': { categoryId: 'subscriptions', subcategoryId: 'subs-streaming', merchant: 'Spotify', tags: ['streaming', 'subscription', 'recurring'] },
  'hulu': { categoryId: 'subscriptions', subcategoryId: 'subs-streaming', merchant: 'Hulu', tags: ['streaming', 'subscription', 'recurring'] },
  'disney': { categoryId: 'subscriptions', subcategoryId: 'subs-streaming', merchant: 'Disney+', tags: ['streaming', 'subscription', 'recurring'] },
  'hbo': { categoryId: 'subscriptions', subcategoryId: 'subs-streaming', merchant: 'HBO Max', tags: ['streaming', 'subscription', 'recurring'] },
  'apple tv': { categoryId: 'subscriptions', subcategoryId: 'subs-streaming', merchant: 'Apple TV+', tags: ['streaming', 'subscription', 'recurring'] },
  'apple music': { categoryId: 'subscriptions', subcategoryId: 'subs-streaming', merchant: 'Apple Music', tags: ['streaming', 'subscription', 'recurring'] },
  'apple one': { categoryId: 'subscriptions', subcategoryId: 'subs-streaming', merchant: 'Apple One', tags: ['streaming', 'subscription', 'recurring'] },
  'icloud': { categoryId: 'subscriptions', subcategoryId: 'subs-software', merchant: 'iCloud', tags: ['software', 'subscription', 'recurring'] },
  'youtube premium': { categoryId: 'subscriptions', subcategoryId: 'subs-streaming', merchant: 'YouTube Premium', tags: ['streaming', 'subscription', 'recurring'] },
  'youtube tv': { categoryId: 'subscriptions', subcategoryId: 'subs-streaming', merchant: 'YouTube TV', tags: ['streaming', 'subscription', 'recurring'] },
  'peacock': { categoryId: 'subscriptions', subcategoryId: 'subs-streaming', merchant: 'Peacock', tags: ['streaming', 'subscription', 'recurring'] },
  'paramount': { categoryId: 'subscriptions', subcategoryId: 'subs-streaming', merchant: 'Paramount+', tags: ['streaming', 'subscription', 'recurring'] },
  'sling tv': { categoryId: 'subscriptions', subcategoryId: 'subs-streaming', merchant: 'Sling TV', tags: ['streaming', 'subscription', 'recurring'] },
  'directv': { categoryId: 'subscriptions', subcategoryId: 'subs-streaming', merchant: 'DirecTV', tags: ['streaming', 'subscription', 'recurring'] },
  'amazon prime': { categoryId: 'subscriptions', subcategoryId: 'subs-streaming', merchant: 'Amazon Prime', tags: ['streaming', 'subscription', 'recurring'] },
  'audible': { categoryId: 'subscriptions', subcategoryId: 'subs-streaming', merchant: 'Audible', tags: ['streaming', 'subscription', 'recurring'] },
  'kindle': { categoryId: 'subscriptions', subcategoryId: 'subs-software', merchant: 'Kindle', tags: ['subscription', 'recurring'] },
  'chatgpt': { categoryId: 'subscriptions', subcategoryId: 'subs-software', merchant: 'ChatGPT', tags: ['software', 'subscription', 'recurring'] },
  'openai': { categoryId: 'subscriptions', subcategoryId: 'subs-software', merchant: 'OpenAI', tags: ['software', 'subscription', 'recurring'] },
  'github': { categoryId: 'subscriptions', subcategoryId: 'subs-software', merchant: 'GitHub', tags: ['software', 'subscription', 'recurring'] },
  'microsoft 365': { categoryId: 'subscriptions', subcategoryId: 'subs-software', merchant: 'Microsoft 365', tags: ['software', 'subscription', 'recurring'] },
  'microsoft office': { categoryId: 'subscriptions', subcategoryId: 'subs-software', merchant: 'Microsoft 365', tags: ['software', 'subscription', 'recurring'] },
  'adobe': { categoryId: 'subscriptions', subcategoryId: 'subs-software', merchant: 'Adobe', tags: ['software', 'subscription', 'recurring'] },
  'dropbox': { categoryId: 'subscriptions', subcategoryId: 'subs-software', merchant: 'Dropbox', tags: ['software', 'subscription', 'recurring'] },
  'google one': { categoryId: 'subscriptions', subcategoryId: 'subs-software', merchant: 'Google One', tags: ['software', 'subscription', 'recurring'] },
  'google storage': { categoryId: 'subscriptions', subcategoryId: 'subs-software', merchant: 'Google Storage', tags: ['software', 'subscription', 'recurring'] },
  'google play': { categoryId: 'subscriptions', subcategoryId: 'subs-software', merchant: 'Google Play', tags: ['software', 'subscription'] },
  'zoom': { categoryId: 'subscriptions', subcategoryId: 'subs-software', merchant: 'Zoom', tags: ['software', 'subscription', 'recurring'] },
  'slack': { categoryId: 'subscriptions', subcategoryId: 'subs-software', merchant: 'Slack', tags: ['software', 'subscription', 'recurring'] },
  'notion': { categoryId: 'subscriptions', subcategoryId: 'subs-software', merchant: 'Notion', tags: ['software', 'subscription', 'recurring'] },
  'duolingo': { categoryId: 'subscriptions', subcategoryId: 'subs-software', merchant: 'Duolingo', tags: ['software', 'subscription', 'education'] },
  'headspace': { categoryId: 'subscriptions', subcategoryId: 'subs-software', merchant: 'Headspace', tags: ['software', 'subscription', 'health'] },
  'calm': { categoryId: 'subscriptions', subcategoryId: 'subs-software', merchant: 'Calm', tags: ['software', 'subscription', 'health'] },
  'nytimes': { categoryId: 'subscriptions', subcategoryId: 'subs-news', merchant: 'New York Times', tags: ['news', 'subscription', 'recurring'] },
  'new york times': { categoryId: 'subscriptions', subcategoryId: 'subs-news', merchant: 'New York Times', tags: ['news', 'subscription', 'recurring'] },
  'wsj': { categoryId: 'subscriptions', subcategoryId: 'subs-news', merchant: 'Wall Street Journal', tags: ['news', 'subscription', 'recurring'] },
  'wall street journal': { categoryId: 'subscriptions', subcategoryId: 'subs-news', merchant: 'Wall Street Journal', tags: ['news', 'subscription', 'recurring'] },
  'washington post': { categoryId: 'subscriptions', subcategoryId: 'subs-news', merchant: 'Washington Post', tags: ['news', 'subscription', 'recurring'] },
  'barre3': { categoryId: 'health', subcategoryId: 'health-fitness', merchant: 'Barre3', tags: ['fitness', 'subscription', 'recurring'] },
  'classpass': { categoryId: 'health', subcategoryId: 'health-fitness', merchant: 'ClassPass', tags: ['fitness', 'subscription', 'recurring'] },
  't-mobile': { categoryId: 'subscriptions', subcategoryId: 'subs-membership', merchant: 'T-Mobile', tags: ['phone', 'subscription', 'recurring'] },
  'tmobile': { categoryId: 'subscriptions', subcategoryId: 'subs-membership', merchant: 'T-Mobile', tags: ['phone', 'subscription', 'recurring'] },
  'verizon': { categoryId: 'subscriptions', subcategoryId: 'subs-membership', merchant: 'Verizon', tags: ['phone', 'subscription', 'recurring'] },
  'at&t': { categoryId: 'subscriptions', subcategoryId: 'subs-membership', merchant: 'AT&T', tags: ['phone', 'subscription', 'recurring'] },
  'att ': { categoryId: 'subscriptions', subcategoryId: 'subs-membership', merchant: 'AT&T', tags: ['phone', 'subscription', 'recurring'] },
  'comcast': { categoryId: 'housing', subcategoryId: 'housing-internet', merchant: 'Comcast / Xfinity', tags: ['internet', 'cable', 'subscription', 'recurring'] },
  'xfinity': { categoryId: 'housing', subcategoryId: 'housing-internet', merchant: 'Xfinity', tags: ['internet', 'cable', 'subscription', 'recurring'] },
  'spectrum': { categoryId: 'housing', subcategoryId: 'housing-internet', merchant: 'Spectrum', tags: ['internet', 'cable', 'subscription', 'recurring'] },
  'cox communications': { categoryId: 'housing', subcategoryId: 'housing-internet', merchant: 'Cox', tags: ['internet', 'cable', 'subscription', 'recurring'] },
  'centurylink': { categoryId: 'housing', subcategoryId: 'housing-internet', merchant: 'CenturyLink', tags: ['internet', 'subscription', 'recurring'] },
  'verizon fios': { categoryId: 'housing', subcategoryId: 'housing-internet', merchant: 'Verizon Fios', tags: ['internet', 'subscription', 'recurring'] },

  // ── Travel ───────────────────────────────────────────────────────────────────
  'airbnb': { categoryId: 'travel', subcategoryId: 'travel-hotels', merchant: 'Airbnb', tags: ['travel', 'lodging'] },
  'marriott': { categoryId: 'travel', subcategoryId: 'travel-hotels', merchant: 'Marriott', tags: ['travel', 'lodging'] },
  'hilton': { categoryId: 'travel', subcategoryId: 'travel-hotels', merchant: 'Hilton', tags: ['travel', 'lodging'] },
  'hyatt': { categoryId: 'travel', subcategoryId: 'travel-hotels', merchant: 'Hyatt', tags: ['travel', 'lodging'] },
  'holiday inn': { categoryId: 'travel', subcategoryId: 'travel-hotels', merchant: 'Holiday Inn', tags: ['travel', 'lodging'] },
  'best western': { categoryId: 'travel', subcategoryId: 'travel-hotels', merchant: 'Best Western', tags: ['travel', 'lodging'] },
  'hampton inn': { categoryId: 'travel', subcategoryId: 'travel-hotels', merchant: 'Hampton Inn', tags: ['travel', 'lodging'] },
  'courtyard': { categoryId: 'travel', subcategoryId: 'travel-hotels', merchant: 'Courtyard by Marriott', tags: ['travel', 'lodging'] },
  'delta air': { categoryId: 'travel', subcategoryId: 'travel-flights', merchant: 'Delta Airlines', tags: ['travel', 'flight'] },
  'united air': { categoryId: 'travel', subcategoryId: 'travel-flights', merchant: 'United Airlines', tags: ['travel', 'flight'] },
  'american airlines': { categoryId: 'travel', subcategoryId: 'travel-flights', merchant: 'American Airlines', tags: ['travel', 'flight'] },
  'southwest': { categoryId: 'travel', subcategoryId: 'travel-flights', merchant: 'Southwest Airlines', tags: ['travel', 'flight'] },
  'alaska air': { categoryId: 'travel', subcategoryId: 'travel-flights', merchant: 'Alaska Airlines', tags: ['travel', 'flight'] },
  'jetblue': { categoryId: 'travel', subcategoryId: 'travel-flights', merchant: 'JetBlue', tags: ['travel', 'flight'] },
  'spirit air': { categoryId: 'travel', subcategoryId: 'travel-flights', merchant: 'Spirit Airlines', tags: ['travel', 'flight'] },
  'frontier air': { categoryId: 'travel', subcategoryId: 'travel-flights', merchant: 'Frontier Airlines', tags: ['travel', 'flight'] },
  'expedia': { categoryId: 'travel', subcategoryId: 'travel-hotels', merchant: 'Expedia', tags: ['travel', 'booking'] },
  'booking.com': { categoryId: 'travel', subcategoryId: 'travel-hotels', merchant: 'Booking.com', tags: ['travel', 'booking'] },
  'vrbo': { categoryId: 'travel', subcategoryId: 'travel-hotels', merchant: 'VRBO', tags: ['travel', 'lodging'] },
  'hotels.com': { categoryId: 'travel', subcategoryId: 'travel-hotels', merchant: 'Hotels.com', tags: ['travel', 'booking'] },
  'tsa precheck': { categoryId: 'travel', subcategoryId: 'travel-activities', merchant: 'TSA PreCheck', tags: ['travel'] },
  'global entry': { categoryId: 'travel', subcategoryId: 'travel-activities', merchant: 'Global Entry', tags: ['travel'] },

  // ── Health & Wellness ────────────────────────────────────────────────────────
  'cvs': { categoryId: 'health', subcategoryId: 'health-pharmacy', merchant: 'CVS', tags: ['pharmacy'] },
  'walgreens': { categoryId: 'health', subcategoryId: 'health-pharmacy', merchant: 'Walgreens', tags: ['pharmacy'] },
  'rite aid': { categoryId: 'health', subcategoryId: 'health-pharmacy', merchant: 'Rite Aid', tags: ['pharmacy'] },
  'planet fitness': { categoryId: 'health', subcategoryId: 'health-fitness', merchant: 'Planet Fitness', tags: ['gym', 'subscription', 'recurring'] },
  'equinox': { categoryId: 'health', subcategoryId: 'health-fitness', merchant: 'Equinox', tags: ['gym', 'subscription', 'recurring'] },
  'peloton': { categoryId: 'health', subcategoryId: 'health-fitness', merchant: 'Peloton', tags: ['fitness', 'subscription', 'recurring'] },
  'anytime fitness': { categoryId: 'health', subcategoryId: 'health-fitness', merchant: 'Anytime Fitness', tags: ['gym', 'subscription', 'recurring'] },
  'la fitness': { categoryId: 'health', subcategoryId: 'health-fitness', merchant: 'LA Fitness', tags: ['gym', 'subscription', 'recurring'] },
  '24 hour fitness': { categoryId: 'health', subcategoryId: 'health-fitness', merchant: '24 Hour Fitness', tags: ['gym', 'subscription', 'recurring'] },
  'ymca': { categoryId: 'health', subcategoryId: 'health-fitness', merchant: 'YMCA', tags: ['gym', 'subscription', 'recurring'] },
  'the mac': { categoryId: 'health', subcategoryId: 'health-fitness', merchant: 'The MAC', tags: ['gym', 'subscription', 'recurring'] },
  'lifetime fitness': { categoryId: 'health', subcategoryId: 'health-fitness', merchant: 'Life Time Fitness', tags: ['gym', 'subscription', 'recurring'] },
  'life time': { categoryId: 'health', subcategoryId: 'health-fitness', merchant: 'Life Time Fitness', tags: ['gym', 'subscription', 'recurring'] },
  'orange theory': { categoryId: 'health', subcategoryId: 'health-fitness', merchant: 'Orangetheory', tags: ['fitness', 'subscription', 'recurring'] },
  'orangetheory': { categoryId: 'health', subcategoryId: 'health-fitness', merchant: 'Orangetheory', tags: ['fitness', 'subscription', 'recurring'] },
  'soul cycle': { categoryId: 'health', subcategoryId: 'health-fitness', merchant: 'SoulCycle', tags: ['fitness', 'subscription', 'recurring'] },
  'onemedical': { categoryId: 'health', subcategoryId: 'health-medical', merchant: 'One Medical', tags: ['medical', 'subscription', 'recurring'] },
  'one medical': { categoryId: 'health', subcategoryId: 'health-medical', merchant: 'One Medical', tags: ['medical', 'subscription', 'recurring'] },
  'penn mutual': { categoryId: 'health', subcategoryId: 'health-insurance', merchant: 'Penn Mutual Life Insurance', tags: ['insurance', 'recurring'] },
  'kaiser': { categoryId: 'health', subcategoryId: 'health-insurance', merchant: 'Kaiser Permanente', tags: ['health-insurance', 'recurring'] },
  'blue cross': { categoryId: 'health', subcategoryId: 'health-insurance', merchant: 'Blue Cross Blue Shield', tags: ['health-insurance', 'recurring'] },
  'aetna': { categoryId: 'health', subcategoryId: 'health-insurance', merchant: 'Aetna', tags: ['health-insurance', 'recurring'] },
  'cigna': { categoryId: 'health', subcategoryId: 'health-insurance', merchant: 'Cigna', tags: ['health-insurance', 'recurring'] },
  'united health': { categoryId: 'health', subcategoryId: 'health-insurance', merchant: 'UnitedHealth', tags: ['health-insurance', 'recurring'] },
  'anthem': { categoryId: 'health', subcategoryId: 'health-insurance', merchant: 'Anthem', tags: ['health-insurance', 'recurring'] },
  'labcorp': { categoryId: 'health', subcategoryId: 'health-medical', merchant: 'LabCorp', tags: ['medical', 'lab'] },
  'quest diagnostics': { categoryId: 'health', subcategoryId: 'health-medical', merchant: 'Quest Diagnostics', tags: ['medical', 'lab'] },
  'therapy': { categoryId: 'health', subcategoryId: 'health-medical', merchant: 'Therapy', tags: ['mental-health', 'medical'] },
  'betterhelp': { categoryId: 'health', subcategoryId: 'health-medical', merchant: 'BetterHelp', tags: ['mental-health', 'subscription', 'recurring'] },
  'talkspace': { categoryId: 'health', subcategoryId: 'health-medical', merchant: 'Talkspace', tags: ['mental-health', 'subscription', 'recurring'] },

  // ── Housing & Utilities ───────────────────────────────────────────────────────
  'pg&e': { categoryId: 'housing', subcategoryId: 'housing-utilities', merchant: 'PG&E', tags: ['electric', 'utility', 'recurring'] },
  'pge ': { categoryId: 'housing', subcategoryId: 'housing-utilities', merchant: 'PGE', tags: ['electric', 'utility', 'recurring'] },
  'pacific gas': { categoryId: 'housing', subcategoryId: 'housing-utilities', merchant: 'PG&E', tags: ['electric', 'utility', 'recurring'] },
  'nw natural': { categoryId: 'housing', subcategoryId: 'housing-utilities', merchant: 'NW Natural Gas', tags: ['gas', 'utility', 'recurring'] },
  'nw natural gas': { categoryId: 'housing', subcategoryId: 'housing-utilities', merchant: 'NW Natural Gas', tags: ['gas', 'utility', 'recurring'] },
  'con edison': { categoryId: 'housing', subcategoryId: 'housing-utilities', merchant: 'Con Edison', tags: ['electric', 'utility', 'recurring'] },
  'duke energy': { categoryId: 'housing', subcategoryId: 'housing-utilities', merchant: 'Duke Energy', tags: ['electric', 'utility', 'recurring'] },
  'dominion energy': { categoryId: 'housing', subcategoryId: 'housing-utilities', merchant: 'Dominion Energy', tags: ['electric', 'utility', 'recurring'] },
  'national grid': { categoryId: 'housing', subcategoryId: 'housing-utilities', merchant: 'National Grid', tags: ['electric', 'utility', 'recurring'] },
  'southern company': { categoryId: 'housing', subcategoryId: 'housing-utilities', merchant: 'Southern Company', tags: ['electric', 'utility', 'recurring'] },
  'georgia power': { categoryId: 'housing', subcategoryId: 'housing-utilities', merchant: 'Georgia Power', tags: ['electric', 'utility', 'recurring'] },
  'florida power': { categoryId: 'housing', subcategoryId: 'housing-utilities', merchant: 'Florida Power & Light', tags: ['electric', 'utility', 'recurring'] },
  'ameren': { categoryId: 'housing', subcategoryId: 'housing-utilities', merchant: 'Ameren', tags: ['electric', 'utility', 'recurring'] },
  'nicor gas': { categoryId: 'housing', subcategoryId: 'housing-utilities', merchant: 'Nicor Gas', tags: ['gas', 'utility', 'recurring'] },
  'peoples gas': { categoryId: 'housing', subcategoryId: 'housing-utilities', merchant: 'Peoples Gas', tags: ['gas', 'utility', 'recurring'] },
  'garbage': { categoryId: 'housing', subcategoryId: 'housing-utilities', merchant: 'Garbage & Recycling', tags: ['utility', 'recurring'] },
  'recycling': { categoryId: 'housing', subcategoryId: 'housing-utilities', merchant: 'Recycling', tags: ['utility', 'recurring'] },
  'waste management': { categoryId: 'housing', subcategoryId: 'housing-utilities', merchant: 'Waste Management', tags: ['utility', 'recurring'] },
  'republic services': { categoryId: 'housing', subcategoryId: 'housing-utilities', merchant: 'Republic Services', tags: ['utility', 'recurring'] },
  'water ': { categoryId: 'housing', subcategoryId: 'housing-utilities', merchant: 'Water Utility', tags: ['utility', 'recurring'] },
  'interstate pest': { categoryId: 'housing', subcategoryId: 'housing-maintenance', merchant: 'Interstate Pest Management', tags: ['home', 'subscription', 'recurring'] },
  'orkin': { categoryId: 'housing', subcategoryId: 'housing-maintenance', merchant: 'Orkin', tags: ['home', 'subscription', 'recurring'] },
  'terminix': { categoryId: 'housing', subcategoryId: 'housing-maintenance', merchant: 'Terminix', tags: ['home', 'subscription', 'recurring'] },
  'adt': { categoryId: 'housing', subcategoryId: 'housing-maintenance', merchant: 'ADT Security', tags: ['home', 'subscription', 'recurring'] },
  'ring ': { categoryId: 'housing', subcategoryId: 'housing-maintenance', merchant: 'Ring', tags: ['home', 'subscription', 'recurring'] },
  'mortgage': { categoryId: 'housing', subcategoryId: 'housing-rent', merchant: 'Mortgage Payment', tags: ['housing', 'recurring'] },
  'rent ': { categoryId: 'housing', subcategoryId: 'housing-rent', merchant: 'Rent', tags: ['housing', 'recurring'] },

  // ── Childcare ────────────────────────────────────────────────────────────────
  'nanny': { categoryId: 'childcare', subcategoryId: 'kids-childcare', merchant: 'Nanny / Childcare', tags: ['childcare', 'recurring'] },
  'daycare': { categoryId: 'childcare', subcategoryId: 'kids-childcare', merchant: 'Daycare', tags: ['childcare', 'recurring'] },
  'child care': { categoryId: 'childcare', subcategoryId: 'kids-childcare', merchant: 'Child Care', tags: ['childcare', 'recurring'] },
  'kindercare': { categoryId: 'childcare', subcategoryId: 'kids-childcare', merchant: 'KinderCare', tags: ['childcare', 'recurring'] },
  'bright horizons': { categoryId: 'childcare', subcategoryId: 'kids-childcare', merchant: 'Bright Horizons', tags: ['childcare', 'recurring'] },
  'gymnastics': { categoryId: 'childcare', subcategoryId: 'kids-activities', merchant: 'Gymnastics', tags: ['kids', 'activity'] },
  'swim lesson': { categoryId: 'childcare', subcategoryId: 'kids-activities', merchant: 'Swim Lessons', tags: ['kids', 'activity'] },

  // ── Education ────────────────────────────────────────────────────────────────
  'tuition': { categoryId: 'education', subcategoryId: 'edu-tuition', merchant: 'Tuition', tags: ['education', 'recurring'] },
  'udemy': { categoryId: 'education', subcategoryId: 'edu-courses', merchant: 'Udemy', tags: ['education', 'subscription'] },
  'coursera': { categoryId: 'education', subcategoryId: 'edu-courses', merchant: 'Coursera', tags: ['education', 'subscription'] },
  'skillshare': { categoryId: 'education', subcategoryId: 'edu-courses', merchant: 'Skillshare', tags: ['education', 'subscription'] },
  'masterclass': { categoryId: 'education', subcategoryId: 'edu-courses', merchant: 'MasterClass', tags: ['education', 'subscription'] },
  'chegg': { categoryId: 'education', subcategoryId: 'edu-books', merchant: 'Chegg', tags: ['education', 'subscription'] },
  'barnes noble': { categoryId: 'education', subcategoryId: 'edu-books', merchant: 'Barnes & Noble', tags: ['books', 'education'] },

  // ── Savings & Investments ─────────────────────────────────────────────────────
  'fidelity': { categoryId: 'savings', subcategoryId: 'savings-brokerage', merchant: 'Fidelity', tags: ['investment', 'savings'] },
  'vanguard': { categoryId: 'savings', subcategoryId: 'savings-brokerage', merchant: 'Vanguard', tags: ['investment', 'savings'] },
  'schwab': { categoryId: 'savings', subcategoryId: 'savings-brokerage', merchant: 'Charles Schwab', tags: ['investment', 'savings'] },
  'robinhood': { categoryId: 'savings', subcategoryId: 'savings-brokerage', merchant: 'Robinhood', tags: ['investment'] },
  'coinbase': { categoryId: 'savings', subcategoryId: 'savings-brokerage', merchant: 'Coinbase', tags: ['crypto', 'investment'] },
  'betterment': { categoryId: 'savings', subcategoryId: 'savings-brokerage', merchant: 'Betterment', tags: ['investment', 'savings', 'recurring'] },
  'wealthfront': { categoryId: 'savings', subcategoryId: 'savings-brokerage', merchant: 'Wealthfront', tags: ['investment', 'savings'] },
  'acorns': { categoryId: 'savings', subcategoryId: 'savings-brokerage', merchant: 'Acorns', tags: ['investment', 'savings', 'recurring'] },
  '401k': { categoryId: 'savings', subcategoryId: 'savings-401k', merchant: '401(k) Contribution', tags: ['retirement', 'savings', 'recurring'] },
  'roth ira': { categoryId: 'savings', subcategoryId: 'savings-401k', merchant: 'Roth IRA', tags: ['retirement', 'savings'] },
  'marcus': { categoryId: 'savings', subcategoryId: 'savings-savings-account', merchant: 'Marcus by Goldman Sachs', tags: ['savings', 'recurring'] },
  'ally bank': { categoryId: 'savings', subcategoryId: 'savings-savings-account', merchant: 'Ally Bank', tags: ['savings', 'recurring'] },
  'high yield': { categoryId: 'savings', subcategoryId: 'savings-savings-account', merchant: 'High Yield Savings', tags: ['savings'] },

  // ── Transfers ────────────────────────────────────────────────────────────────
  'venmo': { categoryId: 'transfer', subcategoryId: 'transfer-internal', merchant: 'Venmo', tags: ['transfer', 'p2p'] },
  'zelle': { categoryId: 'transfer', subcategoryId: 'transfer-internal', merchant: 'Zelle', tags: ['transfer', 'p2p'] },
  'paypal': { categoryId: 'transfer', subcategoryId: 'transfer-internal', merchant: 'PayPal', tags: ['transfer', 'p2p'] },
  'cash app': { categoryId: 'transfer', subcategoryId: 'transfer-internal', merchant: 'Cash App', tags: ['transfer', 'p2p'] },
  'cashapp': { categoryId: 'transfer', subcategoryId: 'transfer-internal', merchant: 'Cash App', tags: ['transfer', 'p2p'] },
  'apple pay cash': { categoryId: 'transfer', subcategoryId: 'transfer-internal', merchant: 'Apple Pay Cash', tags: ['transfer', 'p2p'] },
  'wire transfer': { categoryId: 'transfer', subcategoryId: 'transfer-internal', merchant: 'Wire Transfer', tags: ['transfer'] },
  'ach transfer': { categoryId: 'transfer', subcategoryId: 'transfer-internal', merchant: 'ACH Transfer', tags: ['transfer'] },
  'online transfer': { categoryId: 'transfer', subcategoryId: 'transfer-internal', merchant: 'Online Transfer', tags: ['transfer'] },
  'account transfer': { categoryId: 'transfer', subcategoryId: 'transfer-internal', merchant: 'Account Transfer', tags: ['transfer'] },
  'credit card payment': { categoryId: 'transfer', subcategoryId: 'transfer-payment', merchant: 'Credit Card Payment', tags: ['transfer', 'payment'] },
  'autopay': { categoryId: 'transfer', subcategoryId: 'transfer-payment', merchant: 'AutoPay', tags: ['transfer', 'payment'] },

  // ── Income ───────────────────────────────────────────────────────────────────
  'direct deposit': { categoryId: 'income', subcategoryId: 'income-salary', merchant: 'Direct Deposit', tags: ['income', 'recurring'] },
  'payroll': { categoryId: 'income', subcategoryId: 'income-salary', merchant: 'Payroll', tags: ['income', 'recurring'] },
  'dividend': { categoryId: 'income', subcategoryId: 'income-investment', merchant: 'Dividend', tags: ['income', 'investment'] },
  'interest earned': { categoryId: 'income', subcategoryId: 'income-investment', merchant: 'Interest', tags: ['income', 'investment'] },
  'tax refund': { categoryId: 'income', subcategoryId: 'income-other', merchant: 'Tax Refund', tags: ['income'] },
  'irs treas': { categoryId: 'income', subcategoryId: 'income-other', merchant: 'IRS', tags: ['income', 'government'] },
  'refund': { categoryId: 'income', subcategoryId: 'income-other', merchant: 'Refund', tags: ['refund'] },

  // ── Entertainment ────────────────────────────────────────────────────────────
  'amc theater': { categoryId: 'entertainment', subcategoryId: 'entertainment-events', merchant: 'AMC Theatres', tags: ['movies'] },
  'regal cinema': { categoryId: 'entertainment', subcategoryId: 'entertainment-events', merchant: 'Regal Cinemas', tags: ['movies'] },
  'ticketmaster': { categoryId: 'entertainment', subcategoryId: 'entertainment-events', merchant: 'Ticketmaster', tags: ['events'] },
  'stubhub': { categoryId: 'entertainment', subcategoryId: 'entertainment-events', merchant: 'StubHub', tags: ['events'] },
  'eventbrite': { categoryId: 'entertainment', subcategoryId: 'entertainment-events', merchant: 'Eventbrite', tags: ['events'] },
  'dave & buster': { categoryId: 'entertainment', subcategoryId: 'entertainment-events', merchant: "Dave & Buster's", tags: ['entertainment'] },
  'bowling': { categoryId: 'entertainment', subcategoryId: 'entertainment-sports', merchant: 'Bowling', tags: ['entertainment', 'sports'] },
  'mini golf': { categoryId: 'entertainment', subcategoryId: 'entertainment-sports', merchant: 'Mini Golf', tags: ['entertainment', 'sports'] },
  'steam ': { categoryId: 'entertainment', subcategoryId: 'entertainment-games', merchant: 'Steam', tags: ['gaming'] },
  'xbox': { categoryId: 'entertainment', subcategoryId: 'entertainment-games', merchant: 'Xbox', tags: ['gaming', 'subscription'] },
  'playstation': { categoryId: 'entertainment', subcategoryId: 'entertainment-games', merchant: 'PlayStation', tags: ['gaming', 'subscription'] },
  'nintendo': { categoryId: 'entertainment', subcategoryId: 'entertainment-games', merchant: 'Nintendo', tags: ['gaming'] },
};

export function merchantLookup(description: string): CategorizationResult | null {
  const lower = description.toLowerCase();
  for (const [key, value] of Object.entries(MERCHANT_LOOKUP)) {
    if (lower.includes(key)) {
      return {
        id: '',
        categoryId: value.categoryId,
        subcategoryId: value.subcategoryId,
        normalizedMerchant: value.merchant,
        confidence: 0.95,
        tags: value.tags,
      };
    }
  }
  return null;
}

export function splitIntoBatches<T>(items: T[], batchSize: number): T[][] {
  const batches: T[][] = [];
  for (let i = 0; i < items.length; i += batchSize) {
    batches.push(items.slice(i, i + batchSize));
  }
  return batches;
}

export function applyCategorizationResults(
  transactions: Transaction[],
  results: CategorizationResult[]
): Transaction[] {
  const resultMap = Object.fromEntries(results.map((r) => [r.id, r]));
  return transactions.map((t) => {
    const r = resultMap[t.id];
    if (!r) return t;
    return {
      ...t,
      categoryId: r.categoryId,
      subcategoryId: r.subcategoryId,
      normalizedMerchant: r.normalizedMerchant || t.description,
      confidence: r.confidence,
      tags: r.tags,
    };
  });
}
